# Generated by Django 3.1.1 on 2020-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=0, max_length=1000)),
                ('email', models.CharField(default=0, max_length=1000)),
                ('name', models.CharField(default=0, max_length=1000)),
                ('Portfolio', models.CharField(default=0, max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
