# Generated by Django 3.1.1 on 2020-11-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
