# Generated by Django 3.1.1 on 2020-12-16 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20201216_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('profileImage', models.FileField(blank=True, null=True, upload_to='home/profileimg', verbose_name='')),
                ('sellername', models.CharField(default=0, max_length=1000)),
                ('tag', models.CharField(default='Graphic Designer', max_length=500)),
                ('sellerRating', models.IntegerField(blank=True, default=0)),
                ('products', models.IntegerField(default=0)),
                ('sells', models.IntegerField(default=0)),
                ('earned', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
