# Generated by Django 3.1.3 on 2020-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creater',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='fileformat',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='searchTags',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
