# Generated by Django 3.1.1 on 2020-12-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sellerprofile_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='productType',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='discription',
            field=models.CharField(default='', max_length=500),
        ),
    ]
