# Generated by Django 3.1.1 on 2020-12-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201220_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=1000)),
                ('email', models.CharField(default=0, max_length=1000)),
                ('brief', models.CharField(default=0, max_length=1000)),
                ('budget', models.CharField(default=0, max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
