# Generated by Django 3.1.1 on 2020-12-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isSold',
        ),
        migrations.AddField(
            model_name='product',
            name='number_sell',
            field=models.IntegerField(default=0),
        ),
    ]
