# Generated by Django 3.1.1 on 2020-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
