# Generated by Django 3.1.4 on 2020-12-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_product_number_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='Address',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='City',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='Country',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='Fullname',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='Paypal',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='PostalCode',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='SendInvoices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='State',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='accountdetails',
            field=models.TextField(default=''),
        ),
    ]
