# Generated by Django 3.1.4 on 2020-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201230_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsample',
            name='filetype',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
