# Generated by Django 3.1.4 on 2020-12-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201230_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='Paypal',
        ),
    ]
