# Generated by Django 3.1.4 on 2020-12-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_sellerprofile_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filetype',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
