# Generated by Django 3.1.4 on 2020-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_product_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filetype',
        ),
        migrations.AddField(
            model_name='productsample',
            name='filetype',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
