# Generated by Django 3.1.4 on 2020-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201231_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsample',
            name='filetype',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
