# Generated by Django 3.1.3 on 2021-01-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_productsample_filetype'),
        ('home', '0020_auto_20201231_0939'),
    ]

    operations = [
    ]
