# Generated by Django 3.1.4 on 2021-01-06 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_merge_20210104_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('profileImage', models.FileField(blank=True, null=True, upload_to='home/profileimg', verbose_name='')),
                ('username', models.CharField(default=0, max_length=1000)),
                ('Fullname', models.CharField(default='', max_length=1000)),
                ('Country', models.CharField(default='', max_length=1000)),
                ('State', models.CharField(default='', max_length=1000)),
                ('City', models.CharField(default='', max_length=1000)),
                ('PostalCode', models.CharField(default='', max_length=1000)),
                ('Address', models.CharField(default='', max_length=1000)),
                ('SendInvoices', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
