# Generated by Django 3.1.4 on 2021-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_sellerprofile_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='order_id',
            field=models.CharField(default='000', max_length=1000),
        ),
    ]
