# Generated by Django 3.1.4 on 2021-01-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_myorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='Address2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
