# Generated by Django 3.1.4 on 2021-01-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_sellerprofile_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
