# Generated by Django 3.1.4 on 2021-01-18 09:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_auto_20210117_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(default=0, max_length=1000)),
                ('timeStamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.sellerprofile')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
