# Generated by Django 3.1.4 on 2021-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_payments_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='product',
        ),
        migrations.AddField(
            model_name='payments',
            name='product_ids',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
