# Generated by Django 3.1.4 on 2021-01-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210118_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='payments',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='payments',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.sellerprofile'),
        ),
    ]
