# Generated by Django 3.1.4 on 2021-01-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_payments_qunatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
